# This example uses "zendphpctl.sh" directly
FROM cr.zend.com/zendphp/8.1:ubuntu-20.04-cli
ENV TZ=UTC
COPY finish_install.sh /usr/local/sbin/finish_install.sh
COPY install_pear.sh /usr/local/sbin/install_pear.sh
RUN chmod +x /usr/local/sbin/*.sh
RUN /usr/local/sbin/install_pear.sh
RUN zendphpctl.sh EXT enable ffi pdo
RUN zendphpctl.sh PECL build swoole 30-swoole
RUN chmod +x /usr/local/sbin/*.sh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN /usr/local/sbin/finish_install.sh
CMD /opt/app/swoole/prime_number_gen.php
