version: '3.7'

services:

  web-server:
    container_name: ws
    image: zendphp-jumpstart/nginx
    depends_on: [php-fpm]
    build:
      context: .
      dockerfile: Dockerfile.Nginx
    volumes:
     - ./html:/var/www/html
    working_dir: /var/www/html
    networks:
      httpd_net:
        ipv4_address: 10.10.10.10

  php-fpm:
    container_name: zendphp
    image: zendphp-jumpstart/fpm
    build:
      context: .
      dockerfile: Dockerfile.FPM
      args:
        TIMEZONE: 'Europe/London'
        ZENDPHP_VERSION: 8.1
        ZEND_EXTENSIONS_LIST: 'openssl mbstring gd'
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/fpm-healthcheck.sh"]
      interval: 10s
      timeout: 2s
      retries: 2
    volumes:
     - ./html:/var/www/html
    working_dir: /var/www/html
    networks:
      httpd_net:
        ipv4_address: 10.10.10.20

networks:
  httpd_net:
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"
