apiVersion: v1
kind: Service
metadata:
  namespace: esc
  labels:
    io.esc.service: web-server
  name: web-server
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.esc.service: web-server
status:
  loadBalancer: {}
