ARG OS=ubuntu
ARG OS_VERSION=20.04
ARG ZENDPHP_VERSION=7.4
ARG BASE_IMAGE=cli
FROM cr.zend.com/zendphp/${ZENDPHP_VERSION}:${OS}-${OS_VERSION}-${BASE_IMAGE}
ARG TIMEZONE=UTC
ARG INSTALL_COMPOSER=true
ARG ZEND_EXTENSIONS_LIST=ffi,pdo
ARG PECL_EXTENSIONS_LIST=swoole
ARG POST_BUILD_BASH=/usr/local/sbin/finish_install.sh
ENV TZ=$TIMEZONE \
    YUM_y='-y'
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY finish_install.sh /usr/local/sbin/finish_install.sh
RUN ZendPHPCustomizeWithBuildArgs.sh
