ARG OS=ubuntu
ARG OS_VERSION=20.04
ARG ZENDPHP_VERSION=8.1
ARG BASE_IMAGE=fpm
FROM cr.zend.com/zendphp/${ZENDPHP_VERSION}:${OS}-${OS_VERSION}-${BASE_IMAGE}
ARG TIMEZONE=UTC
ARG INSTALL_COMPOSER=true
ARG SYSTEM_PACKAGES=libyaml-dev
ARG ZEND_EXTENSIONS_LIST=
ARG PECL_EXTENSIONS_LIST=yaml
ARG POST_BUILD_BASH=/usr/local/sbin/finish_install.sh
ENV TZ=$TIMEZONE
ENV YUM_y='-y'
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY finish_fpm.sh /usr/local/sbin/finish_fpm.sh
COPY install_pear.sh /usr/local/sbin/install_pear.sh
RUN chmod +x /usr/local/sbin/*.sh
RUN /usr/local/sbin/install_pear.sh
RUN ZendPHPCustomizeWithBuildArgs.sh
