SET PHP_VER="8.3"
SET HOME_DIR=/home/vagrant
SET HOST_NAME="php-architect.local"
SET HOST_URL=http://$HOST_NAME/
SET HOST_OTHER="sandbox orderapp php-examples apigility"
SET DB_USR=vagrant
SET DB_PWD=vagrant
SET DB_NAM=php3
SET DB_HOST="127.0.0.1"
SET DB_FN="%HOME_DIR%/php3/data/%DB_NAM%.sql"
SET ADMINER_VER="4.8.1"
SET REPO_DIR=/home/vagrant
SET REPO_BACKUP_DIR=/home/vagrant/backup
SET CONTAINER=php_architect
SET CONTAINER_IP="10.10.30.10"
SET CONTAINER_SUBNET="10.10.30.0\/24"
SET CONTAINER_GATEWAY="10.10.30.1"
SET DOCKER_DEFAULT_PLATFORM=linux/amd64
