# -*- mode: ruby -*-
# vi: set ft=ruby :
# Maintained by: doug@unlikelysource.com
# This script will fail early if the box host is not reachable, probably due to a proxy or firewall.
# Provisioning sequence is critical due to dependencies.

VAGRANTFILE_API_VERSION = "2" # The API version
VM_DISPLAY_NAME = "ZendPHP-ZendHQ" # The name applied to the VM in VituralBox

COURSE_NAME = "php-training" # The course name
WORKSPACE= "/home/vagrant" # The target workspace

$script = <<-SCRIPT
echo "Installing prerequisites.."
apt-get -y update
apt-get install -y git net-tools
apt-get -f -y install
apt-get -y full-upgrade
apt-get autoremove
snap install docker
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.auto_detect = true
    end

    config.vm.hostname = COURSE_NAME
    config.vm.box = "gusztavvargadr/ubuntu-desktop"
    config.vm.box_check_update = true
    config.vm.synced_folder ".", "/home/vagrant/Shared", disabled: false
    config.vm.network "forwarded_port", guest: 80, host: 8084, host_ip: "127.0.0.1"
    config.vm.disk :disk, size: "12GB", primary: true

    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.name = VM_DISPLAY_NAME
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        vb.customize ["modifyvm", :id, "--name", VM_DISPLAY_NAME]
        vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
        vb.customize ["modifyvm", :id, "--vram", "128"]
		vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
		vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    end

	config.vm.provision "shell", inline: $script

end

