version: '3.3'

services:

  nginx_mon:
    hostname: nginx_mon
    container_name: nginx_mon
    image: phptraining/nginx_mon
    build:
      context: ./docker
      dockerfile: Dockerfile.NGINX
    ports:
     - "8888:80"
    volumes:
     - .:/home/training
     - ./mezzio:/var/www/mezzio
    restart: always
    working_dir: /home/training
    networks:
      zendphp_mon:
        ipv4_address: 10.10.70.10

  zendphp_mon_1:
    hostname: zendphp_mon_1
    container_name: zendphp_mon_1
    image: phptraining/zendphp_mon_1
    build:
      context: ./docker
      dockerfile: Dockerfile.ZENDPHP1
    ports:
     - "9001:9000"
    volumes:
     - .:/home/training
     - ./mezzio:/var/www/mezzio
    restart: always
    working_dir: /home/training
    networks:
      zendphp_mon:
        ipv4_address: 10.10.70.20

  zendphp_mon_2:
    hostname: zendphp_mon_2
    container_name: zendphp_mon_2
    image: phptraining/zendphp_mon_2
    build:
      context: ./docker
      dockerfile: Dockerfile.ZENDPHP2
    ports:
     - "9002:9000"
    volumes:
     - .:/home/training
     - ./mezzio:/var/www/mezzio
    restart: always
    working_dir: /home/training
    networks:
      zendphp_mon:
        ipv4_address: 10.10.70.30

  zendhq_mon:
    hostname: zendhq_mon
    container_name: zendhq_mon
    image: phptraining/zendhq_mon
    build:
      context: ./docker
      dockerfile: Dockerfile.ZENDHQ
    ports:
     - "10091:10091"
     - "10090:10090"
    volumes:
     - .:/home/training
    restart: always
    working_dir: /home/training
    networks:
      zendphp_mon:
        ipv4_address: 10.10.70.40

networks:
  zendphp_mon:
    ipam:
      driver: default
      config:
        - subnet: "10.10.70.0/24"
