version: '3.3'

services:

  zendphp:
    container_name: zendphp
    image: phptraining/zendphp
    build:
      context: ./docker
      dockerfile: Dockerfile.ZENDPHP
    ports:
     - "8888:80"
    volumes:
     - ./data:/var/lib/data
     - ./mezzio:/var/www/mezzio
     - .:/home/training
    restart: always
    working_dir: /home/training
    networks:
      zendphp_net:
        ipv4_address: 10.10.60.10

  zendhq:
    container_name: zendhq
    image: phptraining/zendhq
    build:
      context: ./docker
      dockerfile: Dockerfile.ZENDHQ
    ports:
     - "10091:10091"
    volumes:
     - .:/home/training
    restart: always
    working_dir: /home/training
    networks:
      zendphp_net:
        ipv4_address: 10.10.60.20

networks:
  zendphp_net:
    ipam:
      driver: default
      config:
        - subnet: "10.10.60.0/24"
