version: '3.3'

services:

  zendphp2:
    container_name: zendphp2
    image: phptraining/zendphp2
    build:
      context: ./docker
      dockerfile: Dockerfile.ZENDPHP
    ports:
     - "8888:80"
    volumes:
     - .:/home/training
    restart: always
    working_dir: /home/training
    networks:
      zendphp_net_2:
        ipv4_address: 10.10.70.10

  zendhq2:
    container_name: zendhq2
    image: phptraining/zendhq2
    build:
      context: ./docker
      dockerfile: Dockerfile.ZENDHQ
    ports:
     - "10091:10091"
    volumes:
     - .:/home/training
    restart: always
    working_dir: /home/training
    networks:
      zendphp_net_2:
        ipv4_address: 10.10.70.20

networks:
  zendphp_net_2:
    ipam:
      driver: default
      config:
        - subnet: "10.10.70.0/24"
