version: '3.3'

services:

  zendphp_mon:
    hostname: zendphp_mon
    container_name: zendphp_mon
    image: phptraining/zendphp_mon
    build:
      context: ./docker
      dockerfile: Dockerfile.ZENDPHP
    ports:
     - "8888:80"
     - "10090:10090"
    volumes:
     - .:/home/training
     - ./mezzio:/var/www/mezzio
    restart: always
    working_dir: /home/training
    networks:
      zendphp_mon:
        ipv4_address: 10.10.70.10

  zendhq_mon:
    hostname: zendhq_mon
    container_name: zendhq_mon
    image: phptraining/zendhq_mon
    build:
      context: ./docker
      dockerfile: Dockerfile.ZENDHQ
    ports:
     - "10091:10091"
    volumes:
     - .:/home/training
    restart: always
    working_dir: /home/training
    networks:
      zendphp_mon:
        ipv4_address: 10.10.70.20

networks:
  zendphp_mon:
    ipam:
      driver: default
      config:
        - subnet: "10.10.70.0/24"
