version: '3.7'

services:

  web-server:
    container_name: ws
    image: zendphp-jumpstart/nginx
    depends_on: [php-fpm]
    build:
      context: .
      dockerfile: Dockerfile.Nginx
    volumes: [code:/var/www/html:nocopy]
    working_dir: /var/www/html
    networks:
      httpd_net:
        ipv4_address: 10.10.10.10

  php-fpm:
    container_name: zendphp
    image: zendphp-jumpstart/fpm
    depends_on: [maria-db]
    build:
      context: .
      dockerfile: Dockerfile.FPM
      args:
        TIMEZONE: 'Europe/London'
        ZENDPHP_VERSION: 8.0
        SYSTEM_PACKAGES: 'netcat'
        ZEND_EXTENSIONS_LIST: 'mysql redis mbstring gd'
        POST_BUILD_BASH: '/post-build.sh'
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/fpm-healthcheck.sh"]
      interval: 10s
      timeout: 2s
      retries: 2
    volumes: [code:/var/www/html:nocopy]
    working_dir: /var/www/html
    networks:
      httpd_net:
        ipv4_address: 10.10.10.20

  maria-db:
    image: zendphp-jumpstart/db
    build:
      context: .
      dockerfile: Dockerfile.DB
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      httpd_net:
        ipv4_address: 10.10.10.30

volumes:
  db-data:
  code:

networks:
  httpd_net:
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"
