version: '3.7'

services:

  web-server:
    container_name: ws
    image: zendphp-esc/nginx
    build: 
      context: .
      dockerfile: Dockerfile.Nginx
    expose:
      - 8080
      - 8081
    ports:
      - "8080:8080"
      - "8081:8081"
    extra_hosts:
      - pma.lcl:127.0.0.1
      - testsc.lcl:127.0.0.1
      - pma.local:127.0.0.1
      - testsc.local:127.0.0.1

  php-fpm:
    container_name: zendphp
    image: zendphp-esc/fpm
    build: 
      context: .
      dockerfile: Dockerfile.FPM
      args:
        TIMEZONE: 'Europe/London'
        ZENDPHP_VERSION: 8.0
        SYSTEM_PACKAGES: 'netcat'
        ZEND_EXTENSIONS_LIST: 'mysql redis mbstring gd'
        POST_BUILD_BASH: '/post-build.sh'
    expose:
      - 9000
      - 9001
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/fpm-healthcheck.sh"]
      interval: 10s
      timeout: 2s
      retries: 2
  
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  db-data:
  redis-data: