FROM mongo:latest
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y clean

COPY ./data/scripts/geonames.sql /tmp/geonames.sql
COPY ./data/scripts/passwordreset.sql /tmp/passwordreset.sql

RUN echo "Building database and assigning permissions ..." && \
    /etc/init.d/mariadb start && \
    sleep 5 && \
    mysql -uroot -e "SOURCE /tmp/geonames.sql;" && \
    mysql -uroot -e "SOURCE /tmp/passwordreset.sql;"
