FROM mariadb:latest
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y clean

COPY ./data/scripts/geonames.sql /docker-entrypoint-initdb.d/geonames.sql
