ARG OS=alpine
ARG OS_VERSION=3.18
ARG ZENDPHP_VERSION=8.2
ARG PHP_VER_ALPINE=82
ARG BASE_IMAGE=fpm
FROM cr.zend.com/zendphp/${ZENDPHP_VERSION}:${OS}-${OS_VERSION}-${BASE_IMAGE}
COPY zendhq.ini.ZENDPHP /tmp/zendhq.ini
RUN \
    echo "Installing the ZendHQ extension..." && \
    zendphpctl ext install zendhq && \
    cp /tmp/zendhq.ini /etc/php/"$PHP_VER_ALPINE"zend/conf.d/10_zendhq.ini
