FROM alpine:latest
RUN \
    echo "Installing basic utils ..." && \
    apk add nano && \
    apk add bash
RUN \
    echo "Installing nginx ..." && \
    apk add nginx && \
    chown -R nginx /var/www
COPY nginx.startup.sh /usr/sbin/startup.sh
COPY nginx.zendphp1.conf /etc/nginx/http.d/zendphp1.conf
COPY nginx.zendphp2.conf /etc/nginx/http.d/zendphp2.conf
RUN chmod +x /usr/sbin/*.sh
ENTRYPOINT /usr/sbin/startup.sh
