ARG OS=alpine
ARG OS_VERSION=3.18
FROM cr.zend.com/zendhq:${OS}-${OS_VERSION}
COPY license /entrypoint.d/license
COPY default_monitor_rules.json /entrypoint.d/default_monitor_rules.json
RUN \
    echo "Installing basic utils ..." && \
    apk add nano && \
    apk add sqlite
