apiVersion: v1
kind: Service
metadata:
  namespace: esc
  name: php-fpm
  labels:
    io.esc.service: php-fpm
spec:
  type: NodePort
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    io.esc.service: php-fpm