apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: esc
  labels:
    io.esc.service: redis-data
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
