apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: esc
  annotations:
    version: 1.19.10
  labels:
    io.esc.service: web-server
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.esc.service: web-server
  strategy: {}
  template:
    metadata:
      labels:
        io.esc.service: web-server
    spec:
      containers:
        - image: eu.gcr.io/zendphp-313619/esc-nginx
          name: web-server
          ports:
            - containerPort: 8080
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
