version: '3.7'

services:

  web-server:
    image: zendphp-esc/nginx
    ports:
      - "8080:8080"
      - "8081:8081"
    extra_hosts:
      - pma.lcl:127.0.0.1
      - testsc.lcl:127.0.0.1
      - pma.local:127.0.0.1
      - testsc.local:127.0.0.1

  php-fpm:
    image: zendphp-esc/fpm
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/fpm-healthcheck.sh"]
      interval: 10s
      timeout: 2s
      retries: 2
  
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db-data:
  redis-data: