apiVersion: v1
kind: Service
metadata:
  namespace: esc
  name: redis
  labels:
    io.esc.service: redis
spec:
  type: NodePort
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.esc.service: redis