apiVersion: v1
kind: Pod
metadata:
  namespace: esc
  annotations:
    redisversion: 6.2.3
  labels:
    io.esc.service: redis
  name: redis
spec:
  containers:
    - image: redis:alpine
      name: redis
      resources: {}
      volumeMounts:
        - mountPath: /data
          name: redis-data
  restartPolicy: OnFailure
  volumes:
    - name: redis-data
      persistentVolumeClaim:
        claimName: redis-data
status: {}
