apiVersion: v1
kind: Pod
metadata:
  namespace: esc
  annotations:
    type: MariaDb
    version: 10.5.6
  labels:
    io.esc.service: db
  name: db
spec:
  containers:
    - env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpw
      image: mariadb
      name: db
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-data
  restartPolicy: OnFailure
  volumes:
    - name: db-data
      persistentVolumeClaim:
        claimName: db-data
status: {}
