apiVersion: v1
kind: Service
metadata:
  namespace: esc
  name: db
  labels:
    io.esc.service: db
spec:
  type: NodePort
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.esc.service: db